### ISSUE TITLE
테스트 관련 이모지 추가 건의

### ISSUE THREAD

**Issue by woin2ee** [HalamLee/easy-gitmoji#1]
#### 테스트 코드 관련 추가&변경&삭제가 있을때 사용할만한 이모지가 추가되었으면 좋겠습니다.
- 이모지는 ✅ (white_check_mark) 또는 🧪 (test_tube)
- description 으로는 테스트 코드 작성 or 테스트 코드 추가 또는 업데이트

이모지 추가에 대해 어떻게 생각하시나요?

**Comment by HalamLee** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/87893624/222758422-dc5fffcf-3c47-4031-bfe5-7401c6790848.png">
다음 사진과 같이 성공하는 테스트 코드와 실패하는 테스트 코드의 이모지 추가했습니다!
